"""`driverdna corners` — the M1 inspectable artifact.

Renders, per cohort: the frozen corner map (IDs, centers, classes from raw
band assignment at build time) and every lap's landmark positions, so
segmentation and identity output can be reviewed by eye long before the M4
reports exist. Deterministic: no wall-clock timestamps.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from driverdna.config import DriverDNAConfig
from driverdna.corners.classify import MS_TO_KMH, classify_speed
from driverdna.corners.identity import build_corner_map
from driverdna.corners.segmenter import CornerSpan, segment_lap
from driverdna.ingest.loader import load_fixture_cohorts
from driverdna.ingest.parser import TelemetryLap

_LANDMARK_COLUMNS = (
    ("entry", "entry"),
    ("brake_start", "brk-start"),
    ("peak_brake", "brk-peak"),
    ("brake_release", "brk-rel"),
    ("turn_in", "turn-in"),
    ("apex", "apex"),
    ("throttle_pickup", "pickup"),
    ("full_throttle", "full-thr"),
    ("exit", "exit"),
)


def _fmt_time(seconds: float) -> str:
    minutes = int(seconds // 60)
    return f"{minutes}:{seconds - 60 * minutes:06.3f}"


def _pos(lap: TelemetryLap, index: int | None) -> str:
    if index is None:
        return "—"
    return f"{(float(lap.lap_dist[index]) % 1.0) * 100:.1f}"


def _lap_label(lap: TelemetryLap) -> str:
    return lap.lap_id or lap.source_path.stem


def build_corners_report(fixtures_dir: Path, config: DriverDNAConfig) -> str:
    lines: list[str] = [
        "# Corner report — segmentation, identity, classification (M1)",
        "",
        "Generated by `driverdna corners` from the fixtures in "
        f"`{fixtures_dir.as_posix()}`. Landmark positions are % of lap "
        "distance. Classes are raw band assignments from the median minimum "
        "corner speed across the build laps (hysteresis applies once a map "
        "has history).",
        "",
    ]
    for cohort in load_fixture_cohorts(fixtures_dir):
        laps_with_spans: list[tuple[TelemetryLap, list[CornerSpan]]] = [
            (lap, segment_lap(lap, config)) for lap in cohort.laps
        ]
        # Mirror the pipeline: the map freezes from the FIRST lap; every lap
        # (including the first) is then matched against it. Unmatched
        # observations are candidates and are counted below, never hidden.
        corner_map = build_corner_map(laps_with_spans[:1], config.identity)

        min_speeds: dict[str, list[float]] = {c.corner_id: [] for c in corner_map.corners}
        apex_counts: dict[str, int] = {c.corner_id: 0 for c in corner_map.corners}
        unmatched = 0
        assignments: list[tuple[TelemetryLap, list[CornerSpan], list[str | None]]] = []
        for lap, spans in laps_with_spans:
            ids = corner_map.match_lap(lap, spans, config.identity)
            assignments.append((lap, spans, ids))
            for span, cid in zip(spans, ids):
                if cid is None:
                    unmatched += 1
                    continue
                min_speeds[cid].append(span.min_speed(lap) * MS_TO_KMH)
                apex_counts[cid] = max(apex_counts[cid], len(span.landmarks.apexes))

        lines += [
            f"## {cohort.car} @ {cohort.track} — "
            f"{len(cohort.laps)} lap{'s' if len(cohort.laps) != 1 else ''}, "
            f"{len(corner_map.corners)} corners",
            "",
            "| ID | center (lap %) | median min speed (km/h) | class | apexes |",
            "|---|---|---|---|---|",
        ]
        for c in corner_map.corners:
            speeds = min_speeds[c.corner_id]
            median = float(np.median(speeds)) if speeds else float("nan")
            cls = classify_speed(median, config.classification).value if speeds else "—"
            lines.append(
                f"| {c.corner_id} | {c.lap_dist * 100:.1f} | "
                f"{median:.1f} | {cls} | {apex_counts[c.corner_id]} |"
            )
        if unmatched:
            lines += ["", f"Unmatched corner observations: {unmatched} (candidates "
                      "for admission; surfaced, never silent)."]
        lines.append("")

        for lap, spans, ids in assignments:
            lines += [
                f"### Lap {_lap_label(lap)} — {_fmt_time(lap.duration_s)}",
                "",
                "| corner | " + " | ".join(label for _, label in _LANDMARK_COLUMNS) + " |",
                "|" + "---|" * (len(_LANDMARK_COLUMNS) + 1),
            ]
            for span, cid in zip(spans, ids):
                cells = [
                    _pos(lap, getattr(span.landmarks, attr))
                    for attr, _ in _LANDMARK_COLUMNS
                ]
                lines.append(f"| {cid or '??'} | " + " | ".join(cells) + " |")
            lines.append("")
    return "\n".join(lines)
