"""The dialect shim: placeholder translation, DDL transform, and the two
silent-corruption risks the Postgres port introduces.

The float-width and collation tests are the important ones. Both defects fail
*quietly* — they produce wrong numbers or reordered reports rather than an
error — so they get assertions that turn them into loud failures.
"""

from __future__ import annotations

import pytest

from conftest import PG_URL, requires_postgres
from driverdna.db import MIGRATIONS, Database
from driverdna.sql import to_pg, to_pg_ddl
from driverdna.store import redact_dsn, resolve_store

# --- placeholder translation ----------------------------------------------


def test_placeholders_become_format_style():
    assert to_pg("SELECT * FROM t WHERE a=? AND b=?") == (
        "SELECT * FROM t WHERE a=%s AND b=%s"
    )


def test_question_mark_inside_a_literal_is_data_not_a_placeholder():
    """A blind replace would corrupt the literal."""
    assert to_pg("SELECT * FROM t WHERE s='what? really' AND a=?") == (
        "SELECT * FROM t WHERE s='what? really' AND a=%s"
    )


def test_doubled_quote_escape_keeps_the_scan_correct():
    sql = "SELECT * FROM t WHERE s='it''s a ? here' AND a=?"
    assert to_pg(sql).endswith("AND a=%s")
    assert "'it''s a ? here'" in to_pg(sql)


def test_double_quoted_identifier_is_respected():
    assert to_pg('SELECT "odd?name" FROM t WHERE a=?') == (
        'SELECT "odd?name" FROM t WHERE a=%s'
    )


def test_bare_percent_is_rejected_loudly():
    """psycopg would misparse it. There is none in this codebase, so hitting
    one means new SQL arrived that this function has not been taught."""
    with pytest.raises(ValueError, match="%"):
        to_pg("SELECT * FROM t WHERE s LIKE '100%'")


def test_translation_is_idempotent_on_placeholderless_sql():
    sql = "SELECT COUNT(*) AS n FROM laps"
    assert to_pg(sql) == sql


# --- DDL transform ---------------------------------------------------------


def test_real_becomes_double_precision():
    """SQLite's REAL is float8; Postgres's REAL is float4. Copying the DDL
    literally would silently round every metric, phase time, GPS coordinate
    and score to ~7 significant digits."""
    out = to_pg_ddl("CREATE TABLE t (v REAL NOT NULL);")
    assert "DOUBLE PRECISION" in out
    assert "REAL" not in out


def test_text_gets_the_bytewise_collation():
    """Postgres orders text by the database collation; a Supabase cluster is
    en_US.UTF-8, which sorts differently from SQLite's bytewise order and
    would reorder every report that iterates cohorts."""
    out = to_pg_ddl("CREATE TABLE t (name TEXT NOT NULL);")
    assert 'TEXT COLLATE "C"' in out


def test_surrogate_keys_become_identity_but_fk_primary_keys_do_not():
    """`INTEGER PRIMARY KEY REFERENCES ...` is a foreign key that happens to
    be the primary key — always supplied explicitly, never generated."""
    surrogate = to_pg_ddl("CREATE TABLE a (pk INTEGER PRIMARY KEY);")
    assert "GENERATED BY DEFAULT AS IDENTITY" in surrogate

    fk_pk = to_pg_ddl("CREATE TABLE b (pk INTEGER PRIMARY KEY REFERENCES a(pk));")
    assert "GENERATED" not in fk_pk
    assert "BIGINT PRIMARY KEY REFERENCES" in fk_pk


def test_identity_is_by_default_not_always():
    """`store copy` must be able to insert explicit primary keys: evidence IDs
    are literally these numbers ("obs:{obs_pk}"), so renumbering would
    invalidate every stored finding, annotation and citation. ALWAYS would
    forbid that."""
    out = to_pg_ddl("CREATE TABLE a (pk INTEGER PRIMARY KEY);")
    assert "BY DEFAULT" in out and "ALWAYS" not in out


def test_every_migration_translates():
    for i, migration in enumerate(MIGRATIONS, start=1):
        out = to_pg_ddl(migration)
        assert "REAL" not in out, f"migration {i:03d} still has a REAL column"


# --- secret handling -------------------------------------------------------


def test_dsn_password_is_redacted():
    assert redact_dsn("postgresql://user:hunter2@db.example.com:5432/x") == (
        "postgresql://user:***@db.example.com:5432/x"
    )


def test_redaction_leaves_a_passwordless_dsn_alone():
    dsn = "postgresql://postgres@127.0.0.1:55432/ddna"
    assert redact_dsn(dsn) == dsn


def test_no_bare_database_url_fallback(monkeypatch):
    """A generic DATABASE_URL from an unrelated project must never silently
    repoint the instrument at the wrong history."""
    monkeypatch.delenv("DRIVERDNA_DATABASE_URL", raising=False)
    monkeypatch.setenv("DATABASE_URL", "postgresql://someone@elsewhere/other")
    assert resolve_store(None) == "driverdna.db"


def test_project_env_var_is_used(monkeypatch):
    monkeypatch.setenv("DRIVERDNA_DATABASE_URL", "postgresql://a@localhost/db")
    assert resolve_store(None) == "postgresql://a@localhost/db"
    assert resolve_store("explicit.db") == "explicit.db"  # --db still wins


# --- against a real Postgres ----------------------------------------------


@requires_postgres
def test_schema_applies_and_matches_sqlite(pg_schema, tmp_path):
    """Both backends must describe the same tables and columns."""
    with Database.open(pg_schema) as pg, Database.open(tmp_path / "x.db") as lite:
        assert pg.dialect.name == "postgres"
        assert pg.schema_version == lite.schema_version == len(MIGRATIONS)

        def tables(db, sql):
            return sorted(r["name"] for r in db.conn.execute(sql))

        pg_tables = tables(
            pg,
            "SELECT tablename AS name FROM pg_tables "
            "WHERE schemaname = ANY(current_schemas(false))",
        )
        lite_tables = tables(
            lite,
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%'",
        )
        assert pg_tables == lite_tables


@requires_postgres
def test_every_text_column_is_bytewise_collated(pg_schema):
    """The guard against report reordering. Fails if a future column is added
    without the collation."""
    with Database.open(pg_schema) as pg:
        rows = pg.conn.execute(
            """SELECT table_name, column_name FROM information_schema.columns
               WHERE table_schema = current_schema()
                 AND data_type = 'text'
                 AND collation_name IS DISTINCT FROM 'C'"""
        ).fetchall()
        assert rows == [], f"text columns without COLLATE \"C\": {rows}"


@requires_postgres
def test_no_float4_columns(pg_schema):
    """float4 would silently truncate every stored measurement."""
    with Database.open(pg_schema) as pg:
        rows = pg.conn.execute(
            """SELECT table_name, column_name FROM information_schema.columns
               WHERE table_schema = current_schema() AND data_type = 'real'"""
        ).fetchall()
        assert rows == [], f"float4 columns would truncate: {rows}"


@requires_postgres
def test_full_precision_survives_a_round_trip(pg_schema):
    """The behavioural form of the same check: a float64 stored and read back
    must be bit-identical, not merely close."""
    import math

    with Database.open(pg_schema) as pg:
        pg.conn.execute("CREATE TABLE precision_probe (v DOUBLE PRECISION)")
        for value in (math.pi, 1.2345678901234567e-8, 9.87654321098765e15):
            pg.conn.execute("INSERT INTO precision_probe VALUES (?)", (value,))
        back = [
            r["v"] for r in pg.conn.execute(
                "SELECT v FROM precision_probe ORDER BY v"
            )
        ]
        assert back == sorted([math.pi, 1.2345678901234567e-8, 9.87654321098765e15])


@requires_postgres
def test_transaction_block_does_not_close_the_connection(pg_schema):
    """psycopg3's `Connection.__exit__` commits *and closes*; sqlite3's does
    not. There are 19 `with self.conn:` blocks, so mapping this wrongly would
    close the connection after the first write. The proxy maps it onto
    `conn.transaction()` instead."""
    with Database.open(pg_schema) as pg:
        with pg.conn:
            pg.conn.execute(
                """INSERT INTO laps (source_file, driver, car, track, role,
                                     n_samples, duration_s, quality_flags)
                   VALUES ('t.csv', 'owner', 'C', 'T', 'self', 1, 1.0, '[]')"""
            )
        assert pg.conn.closed is False
        # ...and the connection is still usable, which is the real assertion.
        assert pg.conn.execute(
            "SELECT COUNT(*) AS n FROM laps"
        ).fetchone()["n"] == 1
