"""`driverdna model` — the M6 inspectable artifact.

Recomputes and persists (M6a's `driver_beliefs` table, via `store_all_beliefs`)
every fundamental's belief for each driver with self laps, then renders a
plain Markdown table: score, confidence, evidence count, trend, signal
status — insufficient/no-signal fundamentals shown with their stated reason,
never omitted. Deterministic: no wall-clock timestamps in the report body.
"""

from __future__ import annotations

from driverdna.config import DriverDNAConfig
from driverdna.db import Database
from driverdna.model.history import SERIES_VERSION, score_history
from driverdna.model.reading import READING_VERSION, build_reading
from driverdna.model.scoring import SCORING_MODEL_VERSION, store_all_beliefs
from driverdna.model.taxonomy import FUNDAMENTALS, TAXONOMY_VERSION


def _fmt_score(value: float | None) -> str:
    return "—" if value is None else f"{value:.1f}"


def _fmt_confidence(value: float) -> str:
    return f"{value * 100:.0f}%"


def build_model_report(db: Database, config: DriverDNAConfig) -> str:
    drivers = [
        r["driver"] for r in db.conn.execute(
            "SELECT DISTINCT driver FROM laps WHERE role='self' AND owner_user_pk=? ORDER BY driver",
            (db.user_pk,)
        ).fetchall()
    ]

    lines = [
        "# Driver Model report — deterministic per-fundamental scoring (M6)",
        "",
        f"Generated by `driverdna model`. Scoring model `{SCORING_MODEL_VERSION}`, "
        f"taxonomy `{TAXONOMY_VERSION}`. Every score ships with its confidence and "
        "evidence count — a model estimate, not a measurement of truth; more "
        "laps (more sessions, tracks, cars) sharpen it. `no_signal` "
        "fundamentals never score, at any confidence.",
        "",
    ]

    if not drivers:
        lines.append("No self laps imported yet — nothing to score.")
        return "\n".join(lines) + "\n"

    for driver in drivers:
        beliefs = store_all_beliefs(db, driver=driver, config=config)
        lines += [
            f"## {driver}",
            "",
            "| fundamental | signal | score | confidence | evidence (laps) | trend | note |",
            "|---|---|---|---|---|---|---|",
        ]
        for fid in sorted(FUNDAMENTALS):
            b = beliefs[fid]
            # A51: `basis_reason` accompanies a real score (which components
            # it rests on, and whether that limit is structural or pending),
            # where `insufficient_reason` means there is no score at all.
            # Only one is ever set.
            note = b.insufficient_reason or b.basis_reason or ""
            lines.append(
                f"| {fid} | {b.signal_status.value} | {_fmt_score(b.score)} | "
                f"{_fmt_confidence(b.confidence)} | {b.evidence_count} | "
                f"{b.trend} | {note} |"
            )
        lines.append("")

        # A51: which end of that table is which. The artifact listed seven
        # scores and, like the UI before it, never said which was the
        # driver's strength.
        reading = build_reading(beliefs, config)
        lines += [f"### {driver} — strongest and weakest (`{READING_VERSION}`)", ""]
        if reading["strongest"]:
            for label, key in (("Strongest", "strongest"), ("Weakest", "weakest")):
                e = reading[key]
                lines.append(
                    f"- **{label}: {e['fundamental']}** — {e['score']:.2f} "
                    f"(confidence {e['confidence']:.2f}, {e['evidence_count']} laps)"
                )
            lines += [
                "",
                f"{reading['separation_points']:.2f} points apart. Ranked within "
                "this driver only — never against other drivers and never "
                "against an absolute standard, because these scores are not "
                "calibrated to any driver population. Only measured "
                "fundamentals take a verdict slot; "
                f"{len(reading['excluded_proxy'])} proxy fundamental(s) are "
                "ranked below but never named, since naming a greatest "
                "weakness from an indirect inference would headline the "
                "least-supported number here.",
                "",
            ]
        else:
            lines += [f"Unavailable: {reading['verdict_reason']}.", ""]

        history = score_history(db, driver=driver, config=config)
        lines += [
            f"### {driver} — score history (`{SERIES_VERSION}`)",
            "",
        ]
        if history["x_axis"]["kind"] == "unavailable":
            lines += [
                "Unavailable: too few dated laps to fill "
                f"`model.history_buckets` ({config.model.history_buckets}) buckets at "
                f"`model.trend_min_laps_per_bucket` ({config.model.trend_min_laps_per_bucket}) "
                "laps each — stated, not guessed.",
                "",
            ]
        else:
            header = "| fundamental | " + " | ".join(history["x_axis"]["labels"]) + " |"
            sep = "|---|" + "---|" * len(history["x_axis"]["labels"])
            lines += [header, sep]
            for fid in sorted(history["series"]):
                points = history["series"][fid]["points"]
                row = " | ".join(_fmt_score(p["score"]) for p in points)
                lines.append(f"| {fid} | {row} |")
            lines += [
                "",
                "lap counts per bucket: "
                + ", ".join(str(n) for n in history["x_axis"]["bucket_lap_counts"]),
                "",
            ]

    return "\n".join(lines) + "\n"
