"""`driverdna model` — the M6 inspectable artifact.

Recomputes and persists (M6a's `driver_beliefs` table, via `store_all_beliefs`)
every fundamental's belief for each driver with self laps, then renders a
plain Markdown table: score, confidence, evidence count, trend, signal
status — insufficient/no-signal fundamentals shown with their stated reason,
never omitted. Deterministic: no wall-clock timestamps in the report body.
"""

from __future__ import annotations

from driverdna.config import DriverDNAConfig
from driverdna.db import Database
from driverdna.model.scoring import SCORING_MODEL_VERSION, store_all_beliefs
from driverdna.model.taxonomy import FUNDAMENTALS, TAXONOMY_VERSION


def _fmt_score(value: float | None) -> str:
    return "—" if value is None else f"{value:.1f}"


def _fmt_confidence(value: float) -> str:
    return f"{value * 100:.0f}%"


def build_model_report(db: Database, config: DriverDNAConfig) -> str:
    drivers = [
        r["driver"] for r in db.conn.execute(
            "SELECT DISTINCT driver FROM laps WHERE role='self' ORDER BY driver"
        ).fetchall()
    ]

    lines = [
        "# Driver Model report — deterministic per-fundamental scoring (M6)",
        "",
        f"Generated by `driverdna model`. Scoring model `{SCORING_MODEL_VERSION}`, "
        f"taxonomy `{TAXONOMY_VERSION}`. Every score ships with its confidence and "
        "evidence count — a model estimate, not a measurement of truth; more "
        "laps (more sessions, tracks, cars) sharpen it. `no_signal` "
        "fundamentals never score, at any confidence.",
        "",
    ]

    if not drivers:
        lines.append("No self laps imported yet — nothing to score.")
        return "\n".join(lines) + "\n"

    for driver in drivers:
        beliefs = store_all_beliefs(db, driver=driver, config=config)
        lines += [
            f"## {driver}",
            "",
            "| fundamental | signal | score | confidence | evidence (laps) | trend | note |",
            "|---|---|---|---|---|---|---|",
        ]
        for fid in sorted(FUNDAMENTALS):
            b = beliefs[fid]
            note = b.insufficient_reason or ""
            lines.append(
                f"| {fid} | {b.signal_status.value} | {_fmt_score(b.score)} | "
                f"{_fmt_confidence(b.confidence)} | {b.evidence_count} | "
                f"{b.trend} | {note} |"
            )
        lines.append("")

    return "\n".join(lines) + "\n"
