"""Dialect translation: one set of SQL, two backends.

Every query in this package is written once, in SQLite's spelling, and
translated here for Postgres. Two transforms are needed and no more, because
the schema was already close to portable — the audit that preceded this found
no `LIKE`, no `%`, no positional row access, and upserts already written as
`ON CONFLICT ... DO UPDATE`.

The DDL transform is deliberately mechanical rather than a hand-written second
schema: one source of truth cannot drift, and `test_schema_parity.py` proves
the two results describe the same tables by introspecting both.

Two of the four type rules exist to stop a silent corruption, not for tidiness:

- **REAL.** SQLite's `REAL` is an 8-byte IEEE double. Postgres's `REAL` is
  4-byte float4. Copying the DDL literally would quietly round every metric,
  phase time, GPS coordinate and score to ~7 significant digits.
- **TEXT.** SQLite orders text bytewise. Postgres orders by the database's
  collation, and a Supabase cluster is `en_US.UTF-8`, under which `MX-5` sorts
  after `MX5` and `gr86` before `GR86` — the reverse of here. Since every
  report iterates cohorts `ORDER BY driver, car, track`, that reorders whole
  sections of the output and breaks the byte-identical determinism guarantee.
  `COLLATE "C"` is Postgres's bytewise collation, so it reproduces SQLite's
  ordering exactly.
"""

from __future__ import annotations

import re
from functools import lru_cache

QMARK = "qmark"
FORMAT = "format"


@lru_cache(maxsize=2048)
def to_pg(sql: str) -> str:
    """Rewrite `?` placeholders to psycopg's `%s`, respecting string literals.

    A `?` inside a quoted literal is data, not a placeholder, so the scan
    tracks quoting rather than doing a blind replace. SQL escapes a quote by
    doubling it, which needs no special case here: the doubled quote closes
    and immediately reopens the literal, leaving the state correct either way.

    A bare `%` is rejected rather than escaped. psycopg would misparse it, and
    there is none in this codebase — so encountering one means new SQL was
    written that this function has not been taught to handle, which is worth
    a loud failure rather than a silent guess.
    """
    if "%" in sql:
        raise ValueError(
            "SQL contains '%', which psycopg treats as a placeholder marker. "
            "Escape it as '%%' and teach sql.to_pg() about it deliberately: "
            f"{sql.strip()[:120]}"
        )

    out: list[str] = []
    quote: str | None = None
    for ch in sql:
        if quote is not None:
            out.append(ch)
            if ch == quote:
                quote = None
        elif ch in ("'", '"'):
            quote = ch
            out.append(ch)
        elif ch == "?":
            out.append("%s")
        else:
            out.append(ch)
    return "".join(out)


# --- DDL ------------------------------------------------------------------

# `INTEGER PRIMARY KEY` is SQLite's rowid alias — an auto-assigned surrogate
# key. Postgres needs that spelled out. BY DEFAULT rather than ALWAYS is
# required, not stylistic: `store copy` must be able to insert explicit pk
# values, because evidence IDs are literally these numbers ("obs:{obs_pk}",
# "incident:{incident_pk}") and renumbering would invalidate every stored
# finding, annotation and citation.
_IDENTITY = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def to_pg_ddl(ddl: str) -> str:
    """Translate one SQLite DDL script into its Postgres equivalent."""
    out = ddl

    # SQLite-only: no Postgres session-level switch disables FK enforcement.
    # It exists in a migration only to let a table-rebuild's DROP TABLE
    # succeed despite another table's dangling FK reference — DROP TABLE
    # ... CASCADE below is the Postgres equivalent of that same bypass.
    out = re.sub(r"^\s*PRAGMA foreign_keys\s*=\s*(ON|OFF);\s*\n?", "", out, flags=re.MULTILINE)

    # A rebuilt table's own CREATE TABLE re-declares its FKs, so cascading
    # past a dependent's constraint here does not lose it permanently.
    out = re.sub(r"\bDROP TABLE (\w+);", r"DROP TABLE \1 CASCADE;", out)

    # Surrogate keys only. `INTEGER PRIMARY KEY REFERENCES ...` is a foreign
    # key that happens to be the primary key (corner_windows, lap_samples) —
    # always supplied explicitly, never generated.
    out = re.sub(r"\bINTEGER PRIMARY KEY(?!\s+REFERENCES)", _IDENTITY, out)

    # A column referencing one of those identity columns must match its width.
    out = re.sub(r"\bINTEGER(\s+(?:NOT NULL\s+)?REFERENCES)", r"BIGINT\1", out)
    out = re.sub(r"\bINTEGER PRIMARY KEY(\s+REFERENCES)", r"BIGINT PRIMARY KEY\1", out)

    out = re.sub(r"\bREAL\b", "DOUBLE PRECISION", out)
    out = re.sub(r"\bBLOB\b", "BYTEA", out)
    # Applied last so it cannot touch the keywords substituted above.
    out = re.sub(r"\bTEXT\b", 'TEXT COLLATE "C"', out)
    return out


def to_pg_migrations(migrations: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(to_pg_ddl(m) for m in migrations)
