"""`driverdna attribution` — the M3 inspectable artifact.

Draft Markdown attribution tables: canonical windows, per-phase baselines
and typical losses, cumulative rollups, and every finding from all three
sources — including suppressed findings with their gate reasons, because a
gate that hides silently is a guess in disguise. Deterministic output.
"""

from __future__ import annotations

import numpy as np

from driverdna.attribution.engine import PHASES, baseline
from driverdna.attribution.ranker import (
    Finding,
    cumulative_loss,
    vs_principle_findings,
    vs_reference_findings,
    vs_self_findings,
)
from driverdna.config import DriverDNAConfig
from driverdna.db import Database
from driverdna.pipeline import phase_windows_from_stored


def _fmt(value: float | None, spec: str = ".3f") -> str:
    return "—" if value is None else format(value, spec)


def _findings_table(findings: list[Finding], extra_cols: list[str]) -> list[str]:
    header = "| finding | " + " | ".join(extra_cols) + " | n | shown |"
    rule = "|" + "---|" * (len(extra_cols) + 3)
    lines = [header, rule]
    for f in findings:
        extras = [
            _fmt(f.details.get(c)) if isinstance(f.details.get(c), float) or f.details.get(c) is None
            else str(f.details.get(c))
            for c in extra_cols
        ]
        shown = "yes" if f.shown else f"no — {f.gate_reason}"
        label = f"{f.corner_id} {f.phase or f.kind}"
        lines.append(f"| {label} | " + " | ".join(extras) + f" | {f.n} | {shown} |")
    return lines


def build_attribution_report(db: Database, config: DriverDNAConfig) -> str:
    cohorts = db.conn.execute(
        """SELECT DISTINCT driver, car, track FROM laps WHERE role='self'
           ORDER BY driver, car, track"""
    ).fetchall()

    lines = [
        "# Attribution report — time-at-distance over canonical windows (M3)",
        "",
        "Generated by `driverdna attribution` from the local DB. Phase times "
        "are measured over each corner's frozen canonical windows (identical "
        "track spans for every lap), never between a lap's own landmarks. "
        "Baselines are outlier-screened; the primary baseline is the median "
        "of the top-3 executions; the single best is shown, labeled. "
        "Suppressed findings are listed with their gate reasons — "
        "\"insufficient data\" is an answer, not an omission.",
        "",
    ]
    for cohort in cohorts:
        driver, car, track = cohort["driver"], cohort["car"], cohort["track"]
        loaded = db.load_corner_map(car=car, track=track)
        if loaded is None:
            continue
        map_pk, _ = loaded
        stored = db.load_corner_windows(map_pk)
        windows_by_corner = {
            cid: phase_windows_from_stored(w) for cid, w in sorted(stored.items())
        }

        lines += [f"## {driver} — {car} @ {track}", ""]

        lines += [
            "### Canonical windows (% lap; frozen with the corner map)",
            "",
            "| corner | entry start | turn-in | apex | exit end |",
            "|---|---|---|---|---|",
        ]
        for cid, w in windows_by_corner.items():
            lines.append(
                f"| {cid} | {_fmt(None if w.entry_start is None else w.entry_start * 100, '.1f')} "
                f"| {_fmt(None if w.turn_in is None else w.turn_in * 100, '.1f')} "
                f"| {w.apex * 100:.1f} "
                f"| {_fmt(None if w.exit_end is None else w.exit_end * 100, '.1f')} |"
            )
        lines.append("")

        lines += [
            "### Phase baselines and typical loss (self laps, seconds)",
            "",
            "| corner | phase | n | median | robust best | single best* | "
            "typical loss | spread | outliers screened |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
        for cid, w in windows_by_corner.items():
            for phase in PHASES:
                if w.window(phase) is None:
                    continue
                history = db.phase_history(
                    car=car, track=track, corner_id=cid, phase=phase,
                    role="self", driver=driver,
                )
                times = [h["time_s"] for h in history]
                base = baseline(times, config.attribution)
                if base is None:
                    continue
                typical = float(np.median([t - base.robust_best_s for t in times]))
                lines.append(
                    f"| {cid} | {phase} | {base.n} | {base.median_s:.3f} "
                    f"| {base.robust_best_s:.3f} | {base.single_best_s:.3f} "
                    f"| {typical:.3f} | {base.spread_s:.3f} | {base.n_outliers} |"
                )
        lines += [
            "",
            "\\* single best is one execution — shown for context, never the "
            "yardstick.",
            "",
        ]

        loss = cumulative_loss(
            db, driver=driver, car=car, track=track,
            windows_by_corner=windows_by_corner, config=config,
        )
        lines += ["### Cumulative typical loss (s per lap vs robust baseline)", ""]
        lines += ["| by phase | s |", "|---|---|"] + [
            f"| {phase} | {loss['by_phase'][phase]:.3f} |"
            for phase in sorted(loss["by_phase"])
        ]
        lines += ["", "| by corner class | s |", "|---|---|"] + [
            f"| {cls} | {loss['by_class'][cls]:.3f} |"
            for cls in sorted(loss["by_class"])
        ]
        if loss["outliers_screened"]:
            screened = ", ".join(
                f"{k} ({v})" for k, v in sorted(loss["outliers_screened"].items())
            )
            lines += ["", f"Outliers screened from baselines (kept in history): {screened}."]
        lines.append("")

        self_findings = vs_self_findings(
            db, driver=driver, car=car, track=track,
            windows_by_corner=windows_by_corner, config=config,
        )
        self_findings.sort(
            key=lambda f: (f.details.get("rank_score") is None,
                           -(f.details.get("rank_score") or 0.0)),
        )
        lines += ["### vs-self — opportunity × repeatability (primary practice signal)", ""]
        lines += _findings_table(
            self_findings, ["opportunity_s", "repeatability", "rank_score"]
        )
        lines.append("")

        principle = vs_principle_findings(
            db, driver=driver, car=car, track=track, config=config
        )
        lines += ["### vs-principle — canon checks (form, never priced in seconds)", ""]
        lines += _findings_table(principle, ["trigger_rate"])
        lines.append("")

        reference = vs_reference_findings(
            db, driver=driver, car=car, track=track,
            windows_by_corner=windows_by_corner, config=config,
        )
        lines += ["### vs-reference — gap to reference (context, not recoverable time)", ""]
        if reference:
            lines += _findings_table(reference, ["gap_median_s", "gap_best_s", "reference_n"])
        else:
            lines.append("No reference laps imported for this cohort.")
        lines.append("")
    return "\n".join(lines)
