"""The `driverdna incidents` inspectable artifact (docs/incidents-report.md).

Lists every detected incident per cohort with its mechanism, confidence, and
the channel evidence at onset — the human-readable face of the deterministic
scan. Determinism: same DB in, byte-identical Markdown out.
"""

from __future__ import annotations

from driverdna.db import Database


def build_incidents_report(db: Database) -> str:
    cohorts = db.conn.execute(
        """SELECT DISTINCT driver, car, track FROM laps WHERE role='self'
           ORDER BY driver, car, track"""
    ).fetchall()

    lines = [
        "# Incident report — spins, offs, and near-stops (deterministic)",
        "",
        "Generated by `driverdna incidents`. Every other telemetry tool "
        "discards these as noise; DriverDNA measures them — an incident is the "
        "richest driver signal on a lap. Each row is a single event (N=1): "
        "detected from the trace, its mechanism named only when the signature "
        "is clean, `unclassified` otherwise. Never a driver trait, never "
        "priced as recoverable time. Reference laps are never scanned.",
        "",
    ]

    for c in cohorts:
        driver, car, track = c["driver"], c["car"], c["track"]
        events = db.incidents_for_cohort(driver=driver, car=car, track=track)
        lines += [f"## {driver} — {car} @ {track}", ""]
        if not events:
            lines += ["No incidents detected — every lap ran clean.", ""]
            continue
        lines += [
            f"{len(events)} incident(s) across this cohort's self laps.",
            "",
            "| lap | corner | signals | mechanism | confidence | min km/h | peak yaw | evidence |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for e in events:
            lines.append(
                f"| {e['lap_id'] or e['lap_pk']} | {e['corner_id'] or '—'} | "
                f"{e['kinds']} | {e['classification']} | {e['confidence']} | "
                f"{e['min_speed_kmh']:.0f} | {e['peak_yaw_rate']:.2f} | {e['incident_id']} |"
            )
        lines.append("")
        # The plain-language read for each, in order — the rationale cites the
        # channels the classification stands on.
        for e in events:
            lines.append(f"- **{e['lap_id']} {e['corner_id'] or ''}** — {e['rationale']}")
        lines.append("")

    return "\n".join(lines)
