"""`driverdna coaching` — the M7 inspectable artifact.

Per self cohort: the headline priority, secondary (moderate/notable/major
not chosen as headline), the silent count (negligible, suppressed), and the
always-offered no_signal self-checks — with triggers and gap bands shown,
so "why this advice, and why this loud" is reviewable by eye. Deterministic:
no wall-clock timestamps.
"""

from __future__ import annotations

from driverdna.coaching.engine import eligible_principles, select_coaching
from driverdna.coaching.ontology import ONTOLOGY_VERSION, PRINCIPLES
from driverdna.config import DriverDNAConfig
from driverdna.db import Database


def _fmt_candidate(c) -> str:
    principle = PRINCIPLES[c.principle_id]
    bits = [f"**{c.principle_id}**"]
    if c.corner_id:
        bits.append(f"({c.corner_id})")
    if c.gap_band:
        unit = "s" if c.magnitude_kind == "seconds_lost" else "CV"
        bits.append(f"— {c.gap_band}, {c.magnitude:.3f} {unit}, n={c.n}")
        if c.thin_evidence:
            bits.append("[thin evidence]")
    bits.append(f"— {principle.driving_principle}")
    return " ".join(bits)


def build_coaching_report(db: Database, config: DriverDNAConfig) -> str:
    cohorts = db.conn.execute(
        """SELECT DISTINCT driver, car, track FROM laps WHERE role='self'
           ORDER BY driver, car, track"""
    ).fetchall()

    lines = [
        "# Coaching report — deterministic eligibility, ranking, gap bands (M7)",
        "",
        f"Generated by `driverdna coaching`. Ontology `{ONTOLOGY_VERSION}`. "
        "Deterministic: eligibility (a real detector/finding/CV trigger), "
        "ranking (the single largest seconds-banded notable/major item "
        "leads), and gap-band tone (negligible/silent, moderate/quiet, "
        "notable-major/loud) are all engine-computed — nothing here is "
        "AI-authored; this is the exact set the coach/chat payload hands "
        "the AI to phrase from.",
        "",
    ]

    if not cohorts:
        lines.append("No self laps imported yet — nothing to coach.")
        return "\n".join(lines) + "\n"

    for cohort in cohorts:
        driver, car, track = cohort["driver"], cohort["car"], cohort["track"]
        candidates = eligible_principles(
            db, driver=driver, car=car, track=track, config=config
        )
        selection = select_coaching(candidates)
        lines += [f"## {driver} — {car} @ {track}", ""]

        lines.append("### Headline")
        lines.append("")
        if selection["headline"] is not None:
            lines.append(f"- {_fmt_candidate(selection['headline'])}")
        else:
            lines.append(f"- {selection['headline_reason']}")
        lines.append("")

        lines.append("### Secondary (quiet — moderate, or notable/major not leading)")
        lines.append("")
        if selection["secondary"]:
            for c in selection["secondary"]:
                lines.append(f"- {_fmt_candidate(c)}")
        else:
            lines.append("- none")
        lines.append("")

        lines.append(
            f"### Silent (negligible, suppressed): {selection['silent_count']}"
        )
        lines.append("")

        lines.append("### Self-checks (no_signal — always offered, never the headline)")
        lines.append("")
        for c in selection["self_checks"]:
            principle = PRINCIPLES[c.principle_id]
            sc = principle.self_check
            lines.append(
                f"- **{c.principle_id}** — {sc.instruction} "
                f"_({sc.label})_"
            )
        lines.append("")

    return "\n".join(lines) + "\n"
