"""`driverdna metrics` — the M2 inspectable artifact.

Dumps, per self cohort and corner: every metric's N/median/spread and the
detector trigger counts, straight from the DB — the numbers later milestones
rank and report, reviewable by eye first. Deterministic: no timestamps.
"""

from __future__ import annotations

from driverdna.db import Database
from driverdna.metrics.technique import METRIC_DEFS, summarize


def build_metrics_report(db: Database) -> str:
    cohorts = db.conn.execute(
        """SELECT DISTINCT driver, car, track FROM laps WHERE role='self'
           ORDER BY driver, car, track"""
    ).fetchall()

    lines = [
        "# Metrics report — deterministic technique measurements (M2)",
        "",
        "Generated by `driverdna metrics` from the local DB. Self laps only; "
        "reference laps never appear here. Spread is the sample standard "
        "deviation across laps (0 with a single lap).",
        "",
    ]
    for cohort in cohorts:
        driver, car, track = cohort["driver"], cohort["car"], cohort["track"]
        classes = db.corner_classes(car=car, track=track)
        table = db.self_metric_table(driver=driver, car=car, track=track)
        detectors = db.self_detector_table(driver=driver, car=car, track=track)
        n_laps = db.conn.execute(
            """SELECT COUNT(*) n FROM laps
               WHERE role='self' AND driver=? AND car=? AND track=?""",
            (driver, car, track),
        ).fetchone()["n"]

        lines += [
            f"## {driver} — {car} @ {track} ({n_laps} lap"
            f"{'s' if n_laps != 1 else ''})",
            "",
        ]
        for corner_id in sorted(table):
            cls = classes.get(corner_id) or "unclassified"
            lines += [
                f"### {corner_id} ({cls})",
                "",
                "| metric | n | median | spread | unit |",
                "|---|---|---|---|---|",
            ]
            for name in METRIC_DEFS:
                s = summarize(table[corner_id].get(name, []))
                if s is None:
                    continue
                unit = METRIC_DEFS[name][0]
                lines.append(
                    f"| {name} | {s.n} | {s.median:.3f} | {s.spread:.3f} | {unit} |"
                )
            trig = detectors.get(corner_id, {})
            if trig:
                summary = ", ".join(
                    f"{d} {t}/{n}" for d, (t, n) in sorted(trig.items())
                )
                lines += ["", f"Detector triggers (lap count): {summary}"]
            lines.append("")
    return "\n".join(lines)
