name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: project-8b8fd512-1fa1-4f1c-8d9
  REGION: northamerica-northeast1
  SERVICE: driverdna

  WORKLOAD_IDENTITY_PROVIDER: 'projects/661663598926/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
  SERVICE_ACCOUNT: 'github-actions-deployer@project-8b8fd512-1fa1-4f1c-8d9.iam.gserviceaccount.com'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: .
          flags: '--allow-unauthenticated --cpu-boost'
          timeout: '600'
          env_vars: |
            DRIVERDNA_SESSION_SECRET=${{ secrets.DRIVERDNA_SESSION_SECRET }}
            DRIVERDNA_DATABASE_URL=${{ secrets.DRIVERDNA_DATABASE_URL }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
